### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by roberto-arista** [roberto-arista/PythonForDesigners#1]
There are many subjects that I would like to address in the future. Here is a short list; feel free to propose more!
+ Colors
+ Matrix Transformations
+ Dealing with time and dates
+ BezierPath()
+ FormattedString()
+ Mechanical Curves
+ Linear and 2d Interpolation
+ Interpolation with mutatorMath

The website could also make use of a few
+ search function
+ the lektor plugins I made for csv tables and Python scripts are barely working

**Comment by MauriceMeilleur** [comment]
Definitely pens! I guess a natural choice, after paths and curves.

**Comment by fooness** [comment]
- animations&thinsp;—&thinsp;think of `setup()`, `update()`, `draw()` in processing, p5.js, openFrameworks
- maybe exporting animations as `.gif`&thinsp;—&thinsp;there’s lots of examples on the drawbot forums
