### ISSUE TITLE
Gutenberg didn't invented moveable types

### ISSUE THREAD

**Issue by Popolon** [roberto-arista/PythonForDesigners#10]
Just on the https://pythonfordesigners.com/chapters/strings-encoding-and-unicode/ chapter. Gutenberg didn't invented moveable type. There was already used by Chinese at least by 11th century ([Bi Sheng](https://en.wikipedia.org/wiki/Bi_Sheng) should be according to sources the inventor), The Uygurs in 12th century, [this was moveable words in this case](https://fr.wikipedia.org/wiki/Fichier:Beijing_printing_museum.Caractères_mobiles_en_ancien_Ouighour.jpg), as the old Uygur script characters are linked in a word. This script  is no more used for Uygur language (they use for several centuries Arabic in China, Cyrillic in neighbour Turkish countries, but some derivative of this script are still used by Mongolians of China (They use Cyrillic in Mongolia and Russia) and some Tungus people (Manchu, Xibe, Evenk...). Koreans also used moved type at least since the15th century, at about the time of the invention of the Hangul/Hangeul script. Gutenberg invented the press and oil ink. Asian print use water ink and press by hand to print since about the 9th century. They also used ink seal for long time, in Europe, wax seals was used until recently (personally don't know when exactly). oil ink need more pressure, so a press, but is also more precise than water ink. Notoriety of Gutenberg in Europe is probably due to the Reconquista, Arabians already printed short Quran text amulets on paper for centuries (and the first print in China was [Buddhic sutras](https://en.wikipedia.org/wiki/Diamond_Sutra)), and Catholics tried to remove then more advanced Arabic Muslim civilisation from Andalusia. They bring lot of sciences to Europe, including what we call Arabian numbers, that come from India, and ancient Greek philosophy, mathematics, physics that was kept and translated and improved by Arabians, but lost by European Christian civilisation, and helped to the beginning of the renaissance.

This manual is great, clear and very well made, I started to spread it. Thank you very much, it will probably useful for lot of people.

**Comment by roberto-arista** [comment]
Hi @Popolon,
thanks for pointing this out!

I am well aware that Gutenberg wasn't the first one to use moveable types, I will edit the text with a little note.
Although I am still convinced that Gutenberg "invented" moveable types, as invention is not just being the first to do something. Especially if we don't have proofs of exchange of the technology between Asia and Europe. 

For example, agriculture was "invented" independently in several different locations on Earth, or the wheel was "invented" at least in two different locations (as far as I remember). I will argue that moveable type was invented in two different places with different nuances, then one technology expanded and grew significantly.

The adjustable mould is the most interesting tool of the entire process, and – as far as I know – that one was surely invented by Gutenberg. 

By the way, I am very happy that you are finding the manual useful : )

**Comment by roberto-arista** [comment]
If you have any resource that you'd like to suggest to integrate the manual's bibliography, let me know in this thread!

**Comment by Popolon** [comment]
The problem is that is was widely used at least in great part of Asia from Korea until Egypt, so in Africa (some Koran short texts as soon as 10th century), and Andalusia (Spain) was really a great door to Arabian/Asian world technologies. A big paper manufacture is well known in Uzbekistan, I believe in Bukhara, the paper followed the silk roads.

I'm not sure what you want to say about adjustable moulds
The Korean moveable type of 1447 (the oldest know still existing sample), Chineses characters are often more little than new Korean one (probably derivates from phagpa used during Sino-Mongolian dynasty of Yuan, derivates itself from Tibetan script. Khubilai Khan (than Marco Polo meet in Beijing (Then Qanbaliq), made this city as capital of China and moved from traditional Mongolian Tengrism (shamanic religion of Turco-Mongolians cultures, to Tibetan form of Buddhism (Vajrayana). He placed the Sakya school (Sakyapa) all around Tibet for its control of Tibet in what's called thirteen myriarchies. So it can write Mongolian language with square characters that can be placed beside Chinese characters, instead of long ligatured words as in Mongolian derivative from Old Uygur. Phagpa script was thrown away at the end of less of one century Yuan dynasty :

Korean 
https://fr.wikipedia.org/wiki/Fichier:Worin_cheon-gang-ji-gok_movable_type_(replica),_1447_-_Korean_Culture_Museum,_Incheon_Airport,_Seoul,_South_Korea_-_DSC00793.JPG

By searching, I found this page speak about another metal moveable type in Korea in 1250: https://tricycle.org/magazine/buddhist-history-moveable-type/

Yuan dynasty banknote printing plate (1287) with Han Chinese script + Phagpa script:
https://fr.wikipedia.org/wiki/Fichier:Yuan_dynasty_banknote_with_its_printing_plate_1287.jpg

In this introduction, (with references in note 4,5,6), it is said that Gutenberg one was probably made after several report of people (business people and missionaries) travelling to China about moveable types:
https://en.wikipedia.org/wiki/Movable_type

In Japan:
1615 suruga ban (駿河版) in Japan, but analects of confucius using korean made moveable type (they both used Chinese characters) was the first print in Japan
https://web.archive.org/web/20200323171515/https://www.jstage.jst.go.jp/article/sfj/61/12/61_12_790/_pdf/-char/ja

Another article with interesting sources, including a picture of the Chinese clay moveable type kept in British Library (didn't know this): 
https://blogs.bl.uk/asian-and-african/2018/05/from-the-page-up-the-peking-gazette-and-the-histories-of-everyday-print-in-east-asia-1.html

**Comment by Popolon** [comment]
A book (from 1925, author died few month after, so public domain, but can only found it here) of an American historian about invention and history of printing (reprint of 1931). He searched how could the print come from china to Europe by the possible different ways. Mongolians and Turks conqueror, both originated from today China and around, bring them in Europe by several way. The first print in France, are 4 or 5 (Chinese) stamps of a Mongolian letter from Argun Khan (in Iran) to French king Philippe Le Bel in 1289 (the author of this book mistakenly dated it from 1300+), [I seen it in Archives nationales in Paris](https://commons.wikimedia.org/wiki/File:Argoun_a_Philippe_Le_Bel.1289.jpg). before that Güyük Khan (in Iran too) send one to pope Innocent IV in 1246, still in Roma, wrote in Persian, with Mongolian script stamp. Both are available on Wikimedia commons. And few other prints goes to Russia by Mongolians. Turks bring printing from Western China to Egypt

https://1lib.fr/book/15884748/5f39b0

**Comment by roberto-arista** [comment]
fixed with https://github.com/roberto-arista/PythonForDesigners/commit/1a781ea7c7ee21e9c64771ba3bf5634ad550692c#diff-4b23fce39519147c733aa3712455528870da93c82ff76b12747234cb559cc035
