### ISSUE TITLE
website’s desktop layout media queries …

### ISSUE THREAD

**Issue by fooness** [roberto-arista/PythonForDesigners#4]
Last night I wondered why pythonfordesigners.com looks the same on my smartphone and my laptop. After seeing some videos in your timeline&thinsp;—&thinsp;having seen the _desktop layout_&thinsp;—&thinsp;I wondered even more.

Maybe you could try decreasing the `max-width:1280px` and `min-width:1281px` in your media queries.

<img width="1280" alt="screenshot 2019-02-05 at 06 49 35" src="https://user-images.githubusercontent.com/11408027/52255897-b8eaef80-2914-11e9-9e80-08ca5d36eaca.png">

**Comment by roberto-arista** [comment]
I believe you are navigating the "tablet" media query, consider this code from variable.scss

```
$break-small: 600px;  // below phone, above tablet
$break-small-plusOne: $break-small +1;
$break-medium: 1280px;  // below tablet, above desktop
$break-medium-plusOne: $break-medium +1;

// mixins breakpoints
@mixin breakpoint($point) {
  @if $point == smartphone {
    @media only screen and (max-width: $break-small) { @content; }
  }
  @if $point == tablet {
    @media only screen and (min-width: $break-small-plusOne) and (max-width: $break-medium) { @content; }
  }
  @if $point == desktop {
    @media only screen and (min-width: $break-medium-plusOne) { @content; }
  }
}
```

the sidebar menu is quite large, so I preferred to break early

**Comment by roberto-arista** [comment]
btw, what's the screen size of your laptop?

**Comment by fooness** [comment]
The screen size is 13 inch. The max-width of my viewport is 1265 px in Firefox and 1280 px in Chromium and Safari. The native resolution, as macOS states it, “looks like 1280 × 800 px” …

PS: I think Firefox substracts a 15 px placeholder for the scrollbar from the available viewport width.
