### ISSUE TITLE
Section 5 code snippet throws error

### ISSUE THREAD

**Issue by neversitdull** [roberto-arista/PythonForDesigners#6]
In Section 5 the second snippet 
```
newPage(100, 100)
rectWidth = 20
rectWidth = rectHeight
rect(10, 10, rectWidth, rectHeight)
# here I reassign the width to a new value
rectHeight = rectHeight + 10
rect(10, 10, rectWidth, rectHeight)
```
throws the following error when running in DrawBot:
```Traceback (most recent call last):
  File "<untitled>", line 3, in <module>
NameError: name 'rectHeight' is not defined
```

I'm assuming that `rectWidth = rectHeight` should actually be `rectHeight = rectWidth`

**Comment by neversitdull** [comment]
Created a pull request for this: #7

**Comment by roberto-arista** [comment]
maybe something like this?

```newPage(100, 100)
rectWidth = 20
rectHeight = rectWidth 
rect(10, 10, rectWidth, rectHeight)
# here I reassign the width to a new value
rectHeight = rectHeight + 10
rect(50, 10, rectWidth, rectHeight)
```

so, both rects are visible

**Comment by neversitdull** [comment]
Unless you're really trying to show the mutable factor that you added 10 to the rect height, I think showing both rects is great! :)

**Comment by roberto-arista** [comment]
solved with https://github.com/roberto-arista/PythonForDesigners/commit/a47d38672b32626a80c522f8e83ca58a7f2788ba
